name: complex-workflow

on: push

jobs:
  job1:
    name: FirstJob
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2

      - name: Step two
        run: env | sort

      - name: Step three
        run: echo Date!

  job2:
    name: SecondJob
    runs-on: windows-latest
      steps:
      - name: Step one
        uses: actions/checkout@v2

      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"

      - name: Step three
        run: echo Date!

  job3:
    name: ThirdJob
    runs-on: macos-latest
      steps:
      - name: Step one
        uses: actions/checkout@v2

      - name: Step two
        run: swift build
          
      - name: Step three
        run: echo Date!

  job4:
    name: FourthJob
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
      steps:
      - name: Step one
        uses: actions/checkout@v2
        
      - name: Step two
        run: env | sort

      - name: Step three
        run: echo Date!



